CREATE TABLE CURSO(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	HORAS INT,
	VALOR FLOAT(10.2),
	ID_PREREQ INT
);

ALTER TABLE CURSOS ADD CONSTRAINT FK_PREREQ
FOREIGN KEY(ID_PREREQ) REFERENCES CURSOS(IDCURSO);

/* PROJETANDO NOME DO CURSO PRE-REQUISITO */

SELECT C.NOME AS "CURSO",
	   C.HORAS AS "CARGA",
	   C.VALOR AS "PRECO",
	   IFNUL(P.NOME, "---") AS "REQUISITO"
FROM CURSO C
LEFT JOIN CURSO P
ON P.IDCURSO = C.ID_PREREQ;
